config/routes.rb
Cilantropic::Application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => 'home#index'

  resources :ingredients, :recipe, :recipe_ingredients
  
  match '/search' => 'Search#search'

  

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :amount, :image
  has_many :recipe_ingredients
  has_many :recipes, :through => :recipe_ingredients 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :content, :image
  belongs_to :cookbook
  has_many :recipe_ingredients
  has_many :ingredients, :through => :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  attr_accessible :ingredient_id, :recipe_id, :amount
  belongs_to :ingredient
  belongs_to :recipe
  delegate :name, to: :ingredient
end

app/models/search.rb
class Search
  # attr_accessible :ingredient_ids, :recipe_ids
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@ingredients = Ingredient.order(:name)
  end
end

app/controllers/ingredient_controller.rb
class IngredientController < ApplicationController
	def index
    @ingredients = Ingredient.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
	def show
		@recipe = Recipe.find(params[:id])

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @recipe }
		end
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		#raise params.inspect
		@ingredients = Ingredient.all
		@selected_ingredient_ids = params[:ingredient_ids]
		@all_recipes = Recipe.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_ingredient-list.html.erb
<h1>What's in your kitchen?</h1>

<ul class="ingredient-list">
<%= form_tag('/search', :method => "post") do %>
    <%-	@ingredients.each do |ingredient| %>
    <li> 
    	<div class="callin"></div>
    	<%= image_tag(ingredient.image) %>
    	<article class="ingredient-name">
	    	<%= check_box_tag("ingredient_ids[]", ingredient.id, false, :class => "ingredient-checkbox") %> 
            <span class="checkmark">&#10003;</span>
            <span class="checkmark-shadow"></span>
	    	<%= label_tag("ingredient_ids", ingredient.name) %>
    	</article>
    </li>
    <%- end %>
    <%= submit_tag "Let's Cook This Bitch like Walter and Jesse!" %>
<% end %>
</ul>

app/views/home/_utility-nav.html.erb
<nav class="utility-nav">
	<ul>
		<% if user_signed_in? %>
		<li>Hi, <strong><%= current_user.email %></strong>!</li>
		<li><a href="/users/sign_out">Logout</a></li>
		<% else %>
		<li><a href="/users/sign_in">Log In</a></li>
		<li><a href="/users/sign_up">Sign up!</a></li>
		<% end %>
	</ul>			
</nav>

app/views/home/index.html.erb
<div class="content">
	<div class="main-header-wrap">
		<header>
			<hgroup>
				<h1>Cilantropic</h1>
				<h2>A recipe site that may or may not have anything to do with cilantro.</h2>
				<section class="fix-utility-nav">
						<%= render 'utility-nav' %>
				</section>
				<div class="heading-overlay"></div>
			</hgroup>
		</header>
		<section class="utility-nav-wrap">
			<%= render 'utility-nav' %>
		</section>
	</div> <!-- main-header-wrap -->
	<section class="ingredients-area">
		<%= render 'ingredient-list' %>
	</section>
</div>

app/views/ingredient/index.html.erb
<h1>Select Ingredients</h1>

<table>
<%  incr = 1 
    @ingredients.each do |ingredient|

      if inc % 3 == 0 %>
        <tr>
      <% end %>
    
      <td><%= ingredient.name %></td>
    
      <% if inc % 3 == 2 %>
        </tr>
      <% end %>
    <% incr = incr + 1 %>

    <% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cilantropic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/maz8ffe.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrap">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cilantropic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/maz8ffe.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrap">
    <div class="signup">
		  <%= yield %>
    </div>
	</div>
</body>
</html>

app/views/recipe/show.html.erb
<div class="content recipe-content">
	<h1><%= @recipe.name %></h1>
	<%= image_tag(@recipe.image) %>
	<div class="recipe-details">
		<h2>You will need:</h2>
	<ul class="ingredient-selection-list">
		<% @recipe.recipe_ingredients.each do |list_ingredient| %>
		<li><%= list_ingredient.name %> &ndash; <em><%= list_ingredient.amount %></em></li>
		<% end %>
	</ul>

	<h2 class="preparation">Preparation:</h2>	
		<%= @recipe.content %>
	</div>
	

</div>

app/views/search/search.html.erb
<div class="content">
	<section class="recipe-results">
		<h1>Here's some stuff you can make!</h1>

		<p>You selected the following ingredients:</p>
		<ul class="selected-ingredients">
			<%- @selected_ingredient_ids.each do |ingredient_id| %>
				<li><%= image_tag(Ingredient.find(ingredient_id).image) %>
					<%= Ingredient.find(ingredient_id).name %></li>
			<%- end %>
		</ul>
		<p>Might we suggest you try the following dope recipes based on your selection?</p>
		<ul class="suggested-recipes">
			<%- @selected_recipes = RecipeIngredient.where(:ingredient_id => @selected_ingredient_ids) %>

			<% recipe_list = [] %>
			<%- @selected_recipes.each do |recipe_item| %>
				<% unless recipe_list.include?(recipe_item.recipe) %>
				<li><%= link_to recipe_item.recipe.name, recipe_path(recipe_item.recipe) %> </li>
				<% recipe_list << recipe_item.recipe %>
				<% end %>
			<%- end %>
		</ul>
	</section>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>